travis:
  secure:
    BINSTAR_TOKEN: GwQmDNtxscJBZKpPNGJUa7dEoI9VYf/GaySnHw6LFws0USheFuEW4w+23YFDm6dN0b0BBrek0vUH20bb1cFOK3VcCWkoBgZ3VCn/fqYkn6fvpV+uFSAvlZlsqXeePkrt0yEUHq0tMI/v0o8zZjBtY/yjnMsZ5cCMAD6kcijVzlJbZQxDwqtVDIxlcMWtND6olKMLz80zoN/mfpWqMBEhI88HwWQQeHbX1vCCnLVZVDhXdcqdE9ZsZMniYnIqrUtQGpk6QIWmnOEOswghPRfe1il9XTcExnctpjvXzXdD6kU6isBTf5T4IYY1HS7r81yMvbMyZt59CsK2U+7/w2LmGUxSJbdFf9iEIpo9Hx83hMU3559eiQ57Sr7Yiiu/niQbrtl7xI2VnH13bMFMIF1EUfnSDasrFbNm3Ejmk3exYduTsUZlq4yP1MdfgctHE4VKl6FFABUsfRECI8IAwW48O+Aq36FWu/GOt3MXaluxBKMdnlurcyOqqhHrk4q6a8Gmqaw7IQJOEEG2HkP2cmuPw5wlHHiWY5glIhPS/sHkZbz0jU3soZ60+wOsI+IF6e0mGWaeRdF0uvUdfqTbCGB+07g9LGabIFJoMgloxwCYb23m4UeO80eMsKCd9PcvyvWO3dCQK99R+EvEeiQOK4BsDhcuOCVU666gCjfX811uy0Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
