travis:
  secure:
    BINSTAR_TOKEN: PeYqlg8rP8CdAtprkUjSR/MajY+KZZvs50M7P6LwmR2ckSxp2rCfhraV+mRESHPskX8eYnI5asP2l44We06T/dIeZnEkC6EXlAl/3uE3IG3XHyZKt9hyX6a4piXzRBee1s5UuTedBiaaWfgeVsCPQWcVL56JQi7QRg6lZ51tKU9c5Bnn3u+WVBJc+3s4OEpC82oOABx/Ns+GzL5orXd6DTDKiMpXVZDQNpefmBVAUrHNc5r5Ebg9Lt6wQyQnWZea/3LlCTe95HYmthlQcxCo7/RoPuYdCL1Xprw3oYKPDnNzATGlbjdieOKayyp3WHwd+PhR/v6RAXxBg9wReOa1tgrrG6S5UEYebsCvc+H9Hz1vJ0Ks1e/xavRNJRB8HuP6H4WWp8MZ3eOU1xAEU5axfVpz8b/Q3askD7IXYhZKCR1+Luej+v+BVVlW9tFrUk7LdiBJHtis0kg3WWD8SUHWgkkxG5sYX8yyU5bE3HSDtGxrfcKVMuKfcKXRZyya0Cwin+dd52uy/Z4u+o0XWgw5GWQHpBXT3Lj0Xs0qI8zW0N0i/t57Ae9GtkzUjNgCmSLaP5lrlVi8cbiSMwuYjIWSX1NvBBY2OuyJSNBj4FEMaE6LKUbJ4hkVxf+COyir5moZkpSMfKt6Vi4+1S8bTc5xJSKFEpIIlgYK3hT4kvIU6Uw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
